let arr = [10, 20, 30, 40]
console.log("original array: " + arr)
arr.push(50)
console.log("push: " + arr)
arr.pop()
console.log("pop: " + arr)
arr.unshift(0)
console.log("unshift: " + arr)
arr.shift()
console.log("shift: " + arr)
console.log("includes 10? " + arr.includes(10))
console.log("index of 10: " + arr.indexOf(10))
let newArr = arr.join()
console.log("array converted to string: " + newArr)